name: Nightly

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-latest
            ext: ""
            arch: tar
            runtime: linux-x64
            tree: ls -d */**
            setup: |
              sudo apt-get update
              sudo apt-get install ninja-build cmake
              ninja --version
              cmake --version
              gcc --version
          - name: Windows
            os: windows-latest
            ext: .exe
            arch: zip
            runtime: win-x64
            tree: tree
            setup: |
              choco install ninja cmake
              ninja --version
              cmake --version

    env:
      proj: "BotwModConverter.Console"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Tree Information Structure
        run: ${{ matrix.config.tree }}

      - name: Install Dependencies
        run: ${{ matrix.config.setup }}

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish Botw Mod Converter
        run: dotnet publish ${{ env.proj }}/${{ env.proj }}.csproj -r ${{ matrix.config.runtime }} --configuration Debug --output ${{ matrix.config.name }} --sc false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: ${{ env.proj }}${{ matrix.config.ext }}
          path: ${{ matrix.config.name }}/${{ env.proj }}${{ matrix.config.ext }}
