name: Nightly

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            name: Linux
            ext: ""
            arch: tar
            runtime: linux-x64
          - os: ubuntu-latest
            name: Windows
            ext: .exe
            arch: zip
            runtime: win-x64

    env:
      proj: "BotwModConverter.Console"

    steps:
      - uses: actions/checkout@master
      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish Botw Mod Converter
        run: dotnet publish ${{ env.proj }}/${{ env.proj }}.csproj -r ${{ matrix.platform.runtime }} --configuration Release --output ${{ matrix.platform.name }} --sc false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: ${{ env.proj }}${{ matrix.platform.ext }}
          path: ${{ matrix.platform.name }}/${{ env.proj }}${{ matrix.platform.ext }}
