name: Nightly

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            name: Linux
            ext: ""
            arch: tar
            runtime: linux-x64
          - os: ubuntu-latest
            name: Windows
            ext: .exe
            arch: zip
            runtime: win-x64

    env:
      proj: "BotwModConverter.Console"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup CMAKE
        uses: jwlawson/actions-setup-cmake@v1.13.1

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        id: mingw
        with:
          platform: x64

      - name: Configure Cead (CMAKE)
        run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=${{ mingw.gcc }} -DCMAKE_CXX_COMPILER:FILEPATH=${{ mingw.gxx }} -S./lib/native -B./lib/native/build -G "MinGW Makefiles"

      - name: Build Cead
        run: cmake --build ./lib/native/build --config Release --target all -j 18

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish Botw Mod Converter
        run: dotnet publish ${{ env.proj }}/${{ env.proj }}.csproj -r ${{ matrix.platform.runtime }} --configuration Release --output ${{ matrix.platform.name }} --sc false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: ${{ env.proj }}${{ matrix.platform.ext }}
          path: ${{ matrix.platform.name }}/${{ env.proj }}${{ matrix.platform.ext }}
